package common.dto;

public enum ResponceErrorCodes {
    ERROR_NONE,
    ERROR_READ_DATA,
    ERROR_NO_DATA,
    ERROR_MULTIPLE_DATA,
    ERROR_PINCODE_INCORRECT,
    ERROR_EXPIRATION_DATE,
    ERROR_CARD_NUMBER
}
